### ISSUE TITLE
Add MeansImplicitUse to Ninject.InjectAttribute

### ISSUE THREAD

**Issue by razenpok** [robv8r/resharper-annotations#15]
### Problem
InjectAttribute is almost always used to mark public methods/properties that are only used inside declaring class, i.e. they always got squiggled by Resharper with warning "Property/Method can be made private".
### Proposal
Provide MeansImplicitUse to InjectAttribute 
### Pros
"Property/Method can be made private" won't show anymore.
### Cons
Members marked by InjectAttribute won't be marked as not used if they are not used anymore.

**Comment by robv8r** [comment]
The use-case seems valid to me.  I'd like to do some testing to see if members decorated with the InjectAttribute but lack a Bind definition would cause Ninject to fail to instantiate the class. 

If Ninject cannot create the object in the above scenario, then it would strengthen your argument. 

There was once a ReSharper extension called Agent Mulder that would silence such warnings when using dependency injection. It went well beyond this simple fix. I don't believe Mulder was updated for R# 9, and I'm not sure why. It may be worth the effort to see if someone came up with a replacement, or if Mulder is a viable upgrade candidate for R# 9+. 

In either case, let me do a little research before moving forward with this issue.

**Comment by robv8r** [comment]
Agent Mulder has been updated to work with newer versions of R#.  Can you try Agent Mulder and see if it fixes the problems you're having?  If not, I'll merge the PR

**Comment by razenpok** [comment]
Yeah, Mulder works like a charm. Thx.
